name: Purge Untagged Images

on:
  registry_package:

jobs:
  purge-untagged-images:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Purge untagged images
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GHCR_TOKEN }}
          organization: ${{ github.repository_owner }}
          container: ${{ github.event.repository.name }}
          prune-untagged: true
